config/routes.rb
Rails.application.routes.draw do
  root 'data#index'

  get 'data/import'

  post 'data/delete' => 'datum#my_import'

  get 'data/import' => 'datum#my_import'

  resources :data do 
    collection {post :import}
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/datum.rb
class Datum < ApplicationRecord
    

    require 'csv'
    require 'activerecord-import/base'
    require 'activerecord-import/active_record/adapters/postgresql_adapter'

    def self.my_import(file)
        data = []
        CSV.foreach(file.path, headers: true) do |row|
            data << Datum.new(row.to_h)
        end
        Datum.import data, recursive: true
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  

  def index
    @data = Datum.all
  end

  def import
    Datum.my_import(params[:file])
    redirect_to root_url, notice: "Successfully Imported Data."
  end


  def delete(header, minimum_index = 0)
    if header.is_a? Integer
      @row.delete_at(header)
    elsif i = index(header, minimum_index)
      @row.delete_at(i)
    else
      []
    end
  end

  private

  def datum_params
    params.require(:datum).permit(attributes: [:country_code, :region_name, :company_name, :description, :last_funding_on, :total_funding_usd])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/views/data/import.html.erb
 <% if @data.present? %>
        <%= form_with model: @datum  do |f| %>
            <div class="flex flex-col items-center my-4">
            <p class="">Remove rows:</p>
            <% data_array = @data.all.map { |n| @data } %>
            <%= f.select(:header, options_for_select(data_array)) %>
            <button><%= f.submit "Remove", method: :delete, class: "border-red-600 rounded bg-red-600 button hover:bg-red-700 px-3 py-2 my-2 text-white" %></button>
            </div>
        <% end %>
    <% end %>

app/views/data/index.html.erb
<%= flash[:notice] %>

<div class="flex flex-col items-center mx-6 my-6">
    <h4 class="text-xl font-bold">Import Data</h4>
<div class="flex-row">
    <button><%= form_tag import_data_path, multipart: true do %></button>
        <%= file_field_tag :file %>
        <button><%= submit_tag "Import file", class: "border-blue-500 rounded bg-blue-500 button hover:bg-blue-600 px-3 py-2 text-white" %></button>
    <% end %>
    </div>
</div>

<% if @data.present? %>
    <%= form_with(model: @datum) do |f| %>
        <div class="flex flex-col items-center my-4">
        <p class="">Remove rows:</p>
        <div class="my-2 mx-2"><%= f.select(:header, options_for_select([['Company Name', 0],['Country', 1], ['Region', 2], ['Description', 3], ['Last Funding', 4], ['Total Funding (USD)', 5]])) %></div>
        <button><%= f.submit "Remove", method: :patch, class: "border-red-600 rounded bg-red-600 button hover:bg-red-700 px-3 py-2 text-white" %></button>
        </div>
    <% end %>
 <% end %>
   
<% if @data.present? %>
    <table class="h-screen bg-white flex-col items-center mx-4 my-4 shadow-lg border">
        <thead>
            <tr>
            <th class="border px-2">Company Name</th>
            <th class="border px-2">Country</th>
            <th class="border px-2">Region</th>
            <th class="border px-2">Description</th>
            <th class="border px-2">Last Funding</th>
            <th class="border px-2">Total Funding (USD)</th>
            </tr>
        </thead>
        <tbody>
            <% @data.each do |datum| %>
            <tr class="flex-row border">
            <th><%= datum.company_name %></th>
            <th class="px-2 py-2 font-normal border"><%= datum.country_code %></th>
            <th class="px-2 py-2 font-normal border"><%= datum.region_name %></th>
            <th class="px-2 py-2 font-normal border"><%= datum.description %></th>
            <th class="px-2 py-2 font-normal border"><%= datum.last_funding_on.try(:strftime, ("%m/%d/20%y")) %></th>
            <th class="px-2 py-2 text-white bg-green-400">$<%= datum.total_funding_usd %></th>
            </tr>
            <% end %>
        </tbody>
    </table>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uploader</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

  <body class="bg-gray-100">
    <%= yield %>
  </body>
</html>